
path: /home/harvanok/bachelor-thesis/Bachelor-Thesis/yolo/dataset
train: train_augm_all
# val: val
val: val_staffMeasure

# Classes
names:
  0: StaffMeasure
  # 0: Notehead
  # 1: Staff
  # 2: StaffMeasure